spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gevin-db?useSSL=false&rewriteBatchedStatements=true
    username: gevin
    password: gevin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
terminal-todo:
  persistence:
    storage: mysql
